#!/bin/bash

sudo iptables -A INPUT -s 10.0.0.74 -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT

sudo iptables -A INPUT -s 10.0.0.75 -j DROP

sudo /sbin/iptables -A INPUT -m mac --mac-source 00:0F:EA:91:04:08 -j DROP

sudo iptables -A INPUT -p tcp --dport 23 -j DROP

sudo iptables -A INPUT -p icmp --icmp-type echo-request -j REJECT 
