#!/bin/bash

sudo iptables -A INPUT -p tcp --dport 80 -j Accept
sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo iptables -I INPUT -p tcp --dport 8080 -j ACCEPT
